2018-10-17 18:19:19.910 -03:00 [INF] Applying migrations for Identity...
2018-10-17 18:19:22.036 -03:00 [INF] Migrations applied.
2018-10-17 18:19:22.037 -03:00 [INF] Filling database with system users and roles...
2018-10-17 18:19:22.502 -03:00 [INF] Database filled.
2018-10-17 18:19:57.540 -03:00 [INF] id de entrada: 1
2018-10-17 18:19:57.653 -03:00 [ERR] An internal error occurred [LogId:e14cf230-85d3-43f6-914b-d05d297d4d9f].
System.InvalidOperationException: ah vsf vai.
   at WebApplication1.Controllers.ValuesController.Get(Int32 id) in C:\_ivanborges\github\temp\WebApplication1\Controllers\ValuesController.cs:line 45
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-17 18:21:00.454 -03:00 [INF] id de entrada: 2
2018-10-17 18:21:00.523 -03:00 [INF] O CPF fornecido está em branco, é inválido ou está em um formato inválido.
Furiza.Base.Core.Domain.BR.Exceptions.CpfInvalidoException: O CPF fornecido está em branco, é inválido ou está em um formato inválido.
   at WebApplication1.Controllers.ValuesController.Get(Int32 id) in C:\_ivanborges\github\temp\WebApplication1\Controllers\ValuesController.cs:line 48
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-17 18:29:43.490 -03:00 [INF] Applying migrations for Identity...
2018-10-17 18:29:44.174 -03:00 [INF] Migrations applied.
2018-10-17 18:29:44.175 -03:00 [INF] Filling database with system users and roles...
2018-10-17 18:29:44.596 -03:00 [INF] Database filled.
2018-10-17 18:30:04.375 -03:00 [INF] id de entrada: 3
2018-10-17 18:30:11.045 -03:00 [INF] id de entrada: 2
2018-10-17 18:30:11.132 -03:00 [INF] O CPF fornecido está em branco, é inválido ou está em um formato inválido.
Furiza.Base.Core.Domain.BR.Exceptions.CpfInvalidoException: O CPF fornecido está em branco, é inválido ou está em um formato inválido.
   at WebApplication1.Controllers.ValuesController.Get(Int32 id) in C:\_ivanborges\github\temp\WebApplication1\Controllers\ValuesController.cs:line 48
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-17 18:30:21.525 -03:00 [INF] id de entrada: 1
2018-10-17 18:30:21.593 -03:00 [ERR] An internal error occurred [LogId:fbaf7755-8a8a-4010-bf2f-eb3d975194ea].
System.InvalidOperationException: ah vsf vai.
   at WebApplication1.Controllers.ValuesController.Get(Int32 id) in C:\_ivanborges\github\temp\WebApplication1\Controllers\ValuesController.cs:line 45
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-17 19:08:35.891 -03:00 [INF] Applying migrations for Identity...
2018-10-17 19:08:37.727 -03:00 [INF] Migrations applied.
2018-10-17 19:08:37.727 -03:00 [INF] Filling database with system users and roles...
2018-10-17 19:08:38.185 -03:00 [INF] Database filled.
2018-10-17 19:11:41.755 -03:00 [INF] Applying migrations for Identity...
2018-10-17 19:11:42.418 -03:00 [INF] Migrations applied.
2018-10-17 19:11:42.420 -03:00 [INF] Filling database with system users and roles...
2018-10-17 19:11:42.883 -03:00 [INF] Database filled.
